version: "3.9"

services:
  jekyll:
    image: starefossen/github-pages
    container_name: jekyll-tutorial
    volumes:
      - $PWD/src:/usr/src/app
    ports:
      - "4000:4000"
    networks:
      - jekyll-frontend
    tty: true
    stdin_open: true

networks:
  jekyll-frontend:
    driver: bridge